FORMAT: 1A
HOST: http://api.aluk.com/

# AluK

Simple use case
Polls is a simple API allowing consumers to view polls and vote in them.

## Initial projects Collection [/project?country=be]

### List All Projects [GET]

+ Response 200 (application/json)


    + Headers

            Item-Count: 2
            Picture-Count: 12
            Pictures-Size: 75700202

    + Body

            {
                "types": [
                    {
                        "id":"1",
                        "translations":[
                            {
                                "lang":"fr",
                                "title":"Commercial"
                            },{
                                "lang":"nl",
                                "title":"Commercieel"
                            }
                        ]
                    }, {
                        "id":"4",
                        "translations":[
                            {
                                "lang":"fr",
                                "title":"\u00c9ducation"
                            },{
                                "lang":"nl",
                                "title":"Scholen"
                            }
                        ]
                    },{
                        "id":"3",
                        "translations":[
                            {
                                "lang":"fr",
                                "title":"Hotellerie"
                            },{
                                "lang":"nl",
                                "title":"Horeca"
                            }
                        ]
                    },{
                        "id":"2",
                        "translations":[
                            {
                                "lang":"fr",
                                "title":"R\u00e9sidentiel"
                            },{
                                "lang":"nl",
                                "title":"Residentieel"
                            }
                        ]
                    }
                ],
                "newOrUpdate":[
                    {
                        "id":"1",
                        "realisation-date":"2007",
                        "translations":[
                            {
                                "lang":"fr",
                                "title":"Copernic",
                                "description":"",
                                "location":"Cournon d\u2019Auvergne, France"
                            },{
                                "lang":"nl",
                                "title":"Copernic",
                                "description":"",
                                "location":"Cournon d\u2019Auvergne, Frankrijk"
                            }
                        ],
                        "type":["1","2"],
                        "images":[
                            {
                                "id":"1",
                                "image":"http://www.aluk.com/uploads/projects/images/copernic_01_1920x1920.jpg",
                                "size":6376763,
                                "translations":[
                                    {
                                        "lang":"fr",
                                        "title":"Example de titre d\u2019image",
                                        "description":"Example de description d\u2019image"
                                    },{
                                        "lang":"nl",
                                        "title":"Sample picture title",
                                        "description":"Sample picture description"
                                    }
                                ]
                            },{
                                "id":"2",
                                "image":"http://www.aluk.com/uploads/projects/images/copernic_02_1920x1920.jpg",
                                "size":6919929,
                                "translations":null
                            },{
                                "id":"3",
                                "image":"http://www.aluk.com/uploads/projects/images/copernic_03_1920x1920.jpg",
                                "size":7881773,
                                "translations":null
                            },{
                                "id":"4",
                                "image":"http://www.aluk.com/uploads/projects/images/copernic_04_1920x1920.jpg",
                                "size":5790614,
                                "translations":null
                            },{
                                "id":"5",
                                "image":"http://www.aluk.com/uploads/projects/images/copernic_05_1920x1920.jpg",
                                "size":5082273,
                                "translations":null
                            },{
                                "id":"6",
                                "image":"http://www.aluk.com/uploads/projects/images/copernic_06_1920x1920.jpg",
                                "size":5038045,
                                "translations":null
                            }
                        ],
                        "products":[
                            {
                                "id":"176"
                            },{
                                "id":"207"
                            }
                        ]
                    },{
                        "id":"2",
                        "realisation-date":"2011",
                        "translations":[
                            {
                                "lang":"fr",
                                "title":"Porsche",
                                "description":"",
                                "location":"Epagny, France"
                            },{
                                "lang":"nl",
                                "title":"Porsche",
                                "description":"",
                                "location":"Epagny, Frankrijk"
                            }
                        ],
                        "type":["1"],
                        "images":[
                            {
                                "id":"7",
                                "image":"http://www.aluk.com/uploads/projects/images/porsche_01_1920x1920.jpg",
                                "size":6184025,
                                "translations":null
                            },{
                                "id":"8",
                                "image":"http://www.aluk.com/uploads/projects/images/porsche_02_1920x1920.jpg",
                                "size":8566728,
                                "translations":null
                            },{
                                "id":"9",
                                "image":"http://www.aluk.com/uploads/projects/images/porsche_03_1920x1920.jpg",
                                "size":5234036,
                                "translations":null
                            },{
                                "id":"10",
                                "image":"http://www.aluk.com/uploads/projects/images/porsche_04_1920x1920.jpg",
                                "size":6208304,
                                "translations":null
                            },{
                                "id":"11",
                                "image":"http://www.aluk.com/uploads/projects/images/porsche_05_1920x1920.jpg",
                                "size":6249912,
                                "translations":null
                            },{
                                "id":"12",
                                "image":"http://www.aluk.com/uploads/projects/images/porsche_06_1920x1920.jpg",
                                "size":6167800,
                                "translations":null
                            }
                        ],
                        "products":[
                            {
                                "id":"207"
                            }
                        ]
                    }
                ],
                "delete":[
                ]
            }

## Check update necessity [/project?country=be%26check=true%26timestamp=1467731234]

### Get update count [GET]

+ Response 200 (application/json)


        {
            "item_count":2,
            "picture_count":5,
            "pictures_size":30044077
        }

## Get update [/project?country=be%26timestamp=1467731234]

### Get update list [GET]

+ Response 200 (application/json)


    + Headers

            Item-Count: 2
            Picture-Count: 5
            Pictures-Size: 30044077

    + Body

            {
                "types": [
                    {
                        "id":"1",
                        "translations":[
                            {
                                "lang":"fr",
                                "title":"Commercial"
                            },{
                                "lang":"nl",
                                "title":"Commercieel"
                            }
                        ]
                    }, {
                        "id":"4",
                        "translations":[
                            {
                                "lang":"fr",
                                "title":"\u00c9ducation"
                            },{
                                "lang":"nl",
                                "title":"Scholen"
                            }
                        ]
                    },{
                        "id":"3",
                        "translations":[
                            {
                                "lang":"fr",
                                "title":"Hotellerie"
                            },{
                                "lang":"nl",
                                "title":"Horeca"
                            }
                        ]
                    },{
                        "id":"2",
                        "translations":[
                            {
                                "lang":"fr",
                                "title":"R\u00e9sidentiel"
                            },{
                                "lang":"nl",
                                "title":"Residentieel"
                            }
                        ]
                    }
                ],
                "newOrUpdate":[
                    {
                        "id":"1",
                        "realisation-date":"2007",
                        "translations":[
                            {
                                "lang":"fr",
                                "title":"Copernic",
                                "description":"",
                                "location":"Cournon d\u2019Auvergne, France"
                            },{
                                "lang":"nl",
                                "title":"Copernic",
                                "description":"",
                                "location":"Cournon d\u2019Auvergne, Frankrijk"
                            }
                        ],
                        "type":["1","2"],
                        "images":[
                            {
                                "id":"1",
                                "image":"http://www.aluk.com/uploads/projects/images/copernic_01_1920x1920.jpg",
                                "size":6376763,
                                "translations":[
                                    {
                                        "lang":"fr",
                                        "title":"Example de titre d\u2019image",
                                        "description":"Example de description d\u2019image"
                                    },{
                                        "lang":"nl",
                                        "title":"Sample picture title",
                                        "description":"Sample picture description"
                                    }
                                ]
                            },{
                                "id":"2",
                                "image":"http://www.aluk.com/uploads/projects/images/copernic_02_1920x1920.jpg",
                                "size":6919929,
                                "translations":null
                            },{
                                "id":"3",
                                "image":"http://www.aluk.com/uploads/projects/images/copernic_03_1920x1920.jpg",
                                "size":7881773,
                                "translations":null
                            },{
                                "id":"5",
                                "image":"http://www.aluk.com/uploads/projects/images/copernic_05_1920x1920.jpg",
                                "size":5082273,
                                "translations":null
                            },{
                                "id":"6",
                                "image":"http://www.aluk.com/uploads/projects/images/copernic_06_1920x1920.jpg",
                                "size":5038045,
                                "translations":null
                            }
                        ],
                        "products":[
                            {
                                "id":"176"
                            },{
                                "id":"207"
                            }
                        ],
                        "deleted_images":[
                            "4"
                        ]
                    }
                ],
                "delete":[
                    "2"
                ]
            }



## Initial products Collection [/product?country=be]

### List All Products [GET]

+ Response 200 (application/json)


    + Headers

            Item-Count: 3
            Picture-Count: 7
            Pictures-Size: 1688632

    + Body

            {
                "types": [{
                    "id": "40",
                    "picture": {
                        "image": "http://www.aluk.com/uploads/products/images/product-balustrade-list_700x443.jpg",
                        "size": 54233
                    },
                    "translations": [{
                        "lang": "en",
                        "title": "Balustrades"
                    }]
                }, {
                    "id": "39",
                    "picture": {
                        "image": "http://www.aluk.com/uploads/products/images/product-conservatory-list_700x443.jpg",
                        "size": 62078
                    },
                    "translations": [{
                        "lang": "en",
                        "title": "Conservatories"
                    }, {
                        "lang": "fr",
                        "title": "V\u00e9randas"
                    }, {
                        "lang": "nl",
                        "title": "Verandasystemen"
                    }]
                }, {
                    "id": "37",
                    "picture": {
                        "image": "http://www.aluk.com/uploads/products/images/product-curtainwall-list_700x443.jpg",
                        "size": 45183
                    },
                    "translations": [{
                        "lang": "en",
                        "title": "Curtain walls"
                    }, {
                        "lang": "fr",
                        "title": "Fa\u00e7ades"
                    }, {
                        "lang": "nl",
                        "title": "Vliesgevelsystemen"
                    }, {
                        "lang": "zh",
                        "title": "\u5e55\u5899"
                    }]
                }, {
                    "id": "34",
                    "picture": [],
                    "translations": [{
                        "lang": "en",
                        "title": "Door"
                    }]
                }, {
                    "id": "33",
                    "picture": {
                        "image": "http://www.aluk.com/uploads/products/images/product-windows-list_700x443.jpg",
                        "size": 40812
                    },
                    "translations": [{
                        "lang": "fr",
                        "title": "Fen\u00eatres et portes"
                    }, {
                        "lang": "nl",
                        "title": "Raam- en deursystemen"
                    }, {
                        "lang": "en",
                        "title": "Windows and doors"
                    }, {
                        "lang": "zh",
                        "title": "\u7a97\u548c\u95e8"
                    }]
                }, {
                    "id": "36",
                    "picture": {
                        "image": "http://www.aluk.com/uploads/products/images/product-foldingdoor-list_700x443.jpg",
                        "size": 50202
                    },
                    "translations": [{
                        "lang": "en",
                        "title": "Folding doors"
                    }, {
                        "lang": "fr",
                        "title": "Portes repliables"
                    }, {
                        "lang": "nl",
                        "title": "Vouwdeursystemen"
                    }, {
                        "lang": "zh",
                        "title": "\u6298\u53e0\u95e8"
                    }]
                }, {
                    "id": "35",
                    "picture": {
                        "image": "http://www.aluk.com/uploads/products/images/product-slidingdoor-list_700x443.jpg",
                        "size": 43748
                    },
                    "translations": [{
                        "lang": "fr",
                        "title": "Portes coulissantes"
                    }, {
                        "lang": "nl",
                        "title": "Schuifdeursystemen"
                    }, {
                        "lang": "en",
                        "title": "Sliding doors"
                    }, {
                        "lang": "zh",
                        "title": "\u63a8\u62c9\u95e8\u7cfb\u7edf"
                    }]
                }, {
                    "id": "38",
                    "picture": {
                        "image": "http://www.aluk.com/uploads/products/images/product-shutterandlouver-list_700x443.jpg",
                        "size": 67977
                    },
                    "translations": [{
                        "lang": "en",
                        "title": "Shutters and louvers"
                    }]
                }],
                "newOrUpdate": [{
                    "id": "604",
                    "name": "Atlas",
                    "picture": "http://www.aluk.com/uploads/products/images/atlas_950x622.png",
                    "thermal_break": false,
                    "non_insulated": false,
                    "wood_solution": false,
                    "bullet_proof": false,
                    "translations": [{
                        "lang": "en",
                        "summary": "A multi-modular conservatory system.",
                        "application": "<p>Atlas offers a solution for most standard conservatory applications.<br />Suitable for new and refurbished housing.</p>\n",
                        "description": "<p>Atlas is a multi-modular conservatory system.</p>\n",
                        "features_user": "<ul>\n  <li>Atlas has been designed in a very modular way to offer three different profiles of inertia.</li>\n  <li>The roof offers a flat outer surface thanks to flat or stylized covers.</li>\n  <li>The system is composed of holding tubular profiles on which the glazing is placed on a PVC T with pressure plates screwed and clipped aluminum cover.</li>\n  <li>Sustainable.</li>\n  <li>Burglarproof.</li>\n  <li>Easy to maintain.</li>\n</ul>\n",
                        "options": "<ul>\n  <li>A wide range of RAL colors is available in different finishes: gloss, matt, texture, structure, anodisation.</li>\n  <li>Bicolor, a different color on the inside and the outside, is possible.</li>\n</ul>\n"
                    }, {
                        "lang": "fr",
                        "summary": "Un syst\u00e8me de toiture v\u00e9randa multi-modulaire.",
                        "application": "<p>Atlas offre une solution pour la plupart des applications standard de v\u00e9randas.<br />Id\u00e9al pour la construction et la r\u00e9novation d\u2019une maison.</p>\n",
                        "description": "<p>Atlas est un syst\u00e8me de toiture de v\u00e9randa multi-modulaire.</p>\n",
                        "features_user": "<ul>\n  <li>Atlas a \u00e9t\u00e9 con\u00e7u de mani\u00e8re tr\u00e8s modulaire et offre 3 profil\u00e9s d\u2019inerties diff\u00e9rentes.</li>\n  <li>La toiture offre une surface ext\u00e9rieure plane gr\u00e2ce aux capots plats ou stylis\u00e9s.</li>\n  <li>Le syst\u00e8me est constitu\u00e9 de profil\u00e9s tubulaires porteurs sur lesquels le vitrage est pos\u00e9 sur un T en PVC avec serreur aluminium viss\u00e9 et capot clip\u00e9.</li>\n  <li>Durable.</li>\n  <li>\u00c9tanche \u00e0 l\u2019eau, au vent et \u00e0 l\u2019air.</li>\n  <li>Anti-effraction.</li>\n</ul>\n",
                        "options": "<ul>\n  <li>Une large gamme de couleurs RAL est disponible en diff\u00e9rentes finitions: brillant, mat, textur\u00e9, structure m\u00e9tallique et anodisation.</li>\n  <li>Toutes les applications bicolores, avec une couleur diff\u00e9rente pour l\u2019int\u00e9rieur et l\u2019ext\u00e9rieur, sont possibles.</li>\n</ul>\n"
                    }, {
                        "lang": "nl",
                        "summary": "Het multi-modulaire verandadak.",
                        "application": "<p>Atlas biedt een oplossing voor de meeste standaard veranda toepassingen.<br />Ideaal voor de bouw en renovatie van een huis.</p>\n",
                        "description": "<p>Atlas is een multi-modulair  verandadaksysteem.</p>\n",
                        "features_user": "<ul>\n  <li>Atlas werd moduleerbaar ontworpen in 3 varianten.</li>\n  <li>De dakbouw wordt aan de buitenzijde vlak gehouden door lage of geprofileerde klemlijstprofielen.</li>\n  <li>Het systeem bestaat uit een draagconstructie van kokervormige profielen waarop de beglazing rust en die zowel bovenaan als onderaan worden bevestigd aan horizontaal geplaatste liggerprofielen.</li>\n  <li>Makkelijk te onderhouden.</li>\n  <li>Duurzaam.</li>\n  <li>Water-wind- en luchtdicht.</li>\n  <li>Inbraakwerend.</li>\n</ul>\n",
                        "options": "<ul>\n  <li>Een breed gamma aan RAL-kleuren is verkrijgbaar in verschillende afwerkingen: glans, mat, textuur, structuurlaken anodisatie.</li>\n  <li>Bicolor, een verschillende kleur aan de binnenkant en de buitenkant, is mogelijk.</li>\n</ul>\n"
                    }],
                    "types": ["39"],
                    "files": [{
                        "id": "254",
                        "file": "http://www.aluk.com/uploads/products/files/atlas.png",
                        "translations": [{
                            "lang": "fr",
                            "title": "Section"
                        }, {
                            "lang": "nl",
                            "title": "Section"
                        }]
                    }],
                    "variations": [{
                        "id": "297",
                        "files": [],
                        "translations": [{
                            "lang": "en",
                            "title": "Atlas"
                        }, {
                            "lang": "fr",
                            "title": "Atlas"
                        }, {
                            "lang": "nl",
                            "title": "Atlas"
                        }],
                        "caracs": {
                            "features": {
                                "thermally_broken": true,
                                "thermal_break_size": "30",
                                "tubular_rafter": true,
                                "glazing_bead": true,
                                "glazing_with_gasket": true,
                                "gutter": true,
                                "post": true,
                                "casement_integration": true,
                                "sliding_integration": true,
                                "door_integration": true,
                                "folding_door_integration": true
                            }
                        }
                    }],
                    "projects": []
                }, {
                    "id": "628",
                    "name": "Kolos HI",
                    "picture": "http://www.aluk.com/uploads/products/images/kolos_950x622.png",
                    "thermal_break": false,
                    "non_insulated": false,
                    "wood_solution": false,
                    "bullet_proof": false,
                    "translations": [{
                        "lang": "en",
                        "summary": "A high insulated sliding door system with Spidertechnology.",
                        "application": "<p>Suitable for most standard sliding applications. Ideal for commercial and heavy public sectors, including offices, hospitals, schools and other industrial applications.<br />Suitable for new and refurbished housing.</p>\n",
                        "description": "<p>Kolos is a high insulation sliding window system.</p>\n",
                        "features_user": "<ul>\n  <li>Despite its maximum sash load of 400 kg, the Kolos keeps its natural sleek design.</li>\n  <li>100% compatible with the Triton HI window and door system.</li>\n  <li>Available in monorail, two or three rails, and lift and slide.</li>\n  <li>A 5-point locking system is the standard and can be equipped of anti-burglar glazing beads.</li>\n  <li>Easy to maintain.</li>\n  <li>Sustainable.</li>\n  <li>Air, wind and water tightness.</li>\n</ul>\n",
                        "options": "<ul>\n  <li>A wide range of RAL colors is available in different finishes: gloss, matt, texture, structure, anodisation.</li>\n  <li>Bicolor, a different color on the inside and the outside, is possible.</li>\n</ul>\n"
                    }, {
                        "lang": "fr",
                        "summary": "La porte coulissante hyper isolante avec Spidertechnology.",
                        "application": "<p>Kolos offre une solution adapt\u00e9e \u00e0 la plupart des applications standard de coullissants. Id\u00e9al pour une gamme d\u2019applications des secteurs commercial et public lourds, y compris les bureaux, les h\u00f4pitaux, les \u00e9coles et d\u2019autres applications industrielles.<br />construction et r\u00e9novation d\u2019une maison.</p>\n",
                        "description": "<p>Kolos est le premier syst\u00e8me hyper-isolant pour ch\u00e2ssis coulissants.</p>\n",
                        "features_user": "<ul>\n  <li>En d\u00e9pit du poids maximum par ouvrant de 400 kg, le syst\u00e8me Kolos conserve sa finesse naturelle.</li>\n  <li>100% compatible avec le syst\u00e8me de portes et de fen\u00eatres Triton Hi.</li>\n  <li>Kolos propose des coulissants monorails,  2 rails et un syst\u00e8me levant-coulissant.</li>\n  <li>Une fermeture \u00e0 5 points est le standard et peut \u00eatre \u00e9quip\u00e9 de parcloses antieffraction.</li>\n  <li>Facile \u00e0 entretenir.</li>\n  <li>Durable.</li>\n  <li>\u00c9tanche \u00e0 l\u2019eau, au vent et \u00e0 l\u2019air.</li>\n</ul>\n",
                        "options": "<ul>\n  <li>Une large gamme de couleurs RAL est disponible en diff\u00e9rentes finitions: brillant, mat, textur\u00e9, structure m\u00e9tallique et anodisation.</li>\n  <li>Toutes les applications bicolores, avec une couleur diff\u00e9rente pour l\u2019int\u00e9rieur et l\u2019ext\u00e9rieur, sont possibles.</li>\n</ul>\n"
                    }, {
                        "lang": "nl",
                        "summary": "Hyperisolerende schuifeur met Spidertechnologie.",
                        "application": "<p>Kolos biedt een oplossing voor de meeste standaard raam-en deur oplossingen. Ideaal voor intensief gebruik, zoals in kantoren, ziekenhuizen, scholen en andere industri\u00eble toepassingen.<br />Bouw en renovatie van een woning.<br />Ideaal voor lage-energiewoningen of passiefwoningen.</p>\n",
                        "description": "<p>Kolos is het eerste hoog isolerend schuifdeursysteem.</p>\n",
                        "features_user": "<ul>\n  <li>Hefschuifvleugelgewichten tot 400 kg zijn mogelijk zelfs in combinatie met een slank uiterlijk.</li>\n  <li>Kolos  perfect compatibel en combineerbaar met het Triton HI raam- en deursysteem.</li>\n  <li>Kolos is verkrijgbaar in zowel mono- als duo uitvoering, een hefschuif uitvoering is voorzien.</li>\n  <li>Standaard met een 5-puntsluiting uitgerust en ook inbraakvertragende glaslatten zijn toepasbaar.</li>\n  <li>Makkelijk te onderhouden.</li>\n  <li>Duurzaam.</li>\n  <li>Water-wind- en luchtdicht.</li>\n  <li>Inbraakwerend.</li>\n</ul>\n",
                        "options": "<ul>\n  <li>Een breed gamma aan RAL-kleuren is verkrijgbaar in verschillende afwerkingen: glans, mat, textuur, structuurlaken anodisatie.</li>\n  <li>Bicolor, een verschillende kleur aan de binnenkant en de buitenkant, is mogelijk.</li>\n</ul>\n"
                    }],
                    "types": ["35"],
                    "files": [{
                        "id": "266",
                        "file": "http://www.aluk.com/uploads/products/files/kolos_duo_rail.jpg",
                        "translations": [{
                            "lang": "fr",
                            "title": "Kolos duo rail"
                        }, {
                            "lang": "nl",
                            "title": "Kolos duo rail"
                        }]
                    }, {
                        "id": "267",
                        "file": "http://www.aluk.com/uploads/products/files/kolos_chicane.jpg",
                        "translations": [{
                            "lang": "fr",
                            "title": "Kolos chicane"
                        }, {
                            "lang": "nl",
                            "title": "Kolos chicane"
                        }]
                    }],
                    "variations": [{
                        "id": "295",
                        "files": [],
                        "translations": [{
                            "lang": "en",
                            "title": "Sliding door"
                        }, {
                            "lang": "fr",
                            "title": "Porte coulissante"
                        }, {
                            "lang": "nl",
                            "title": "Schuifdeur"
                        }],
                        "caracs": {
                            "performances": {
                                "uw_double_glazing": "1,5",
                                "uw_triple_glazing": "1,2",
                                "uf": "2,5 (sash in.) / 3,2 (sash out.)",
                                "classification_aww": "4 / E750A / C4"
                            },
                            "sizelimits": {
                                "max_glass_thick": "57",
                                "max_sash_width": "3500",
                                "max_sash_height": "4000",
                                "max_sash_load": "400"
                            },
                            "features": {
                                "multi_point_locking": true,
                                "dual_color": true
                            }
                        }
                    }],
                    "projects": [{
                        "id": "224"
                    }, {
                        "id": "225"
                    }]
                }, {
                    "id": "677",
                    "name": "Vent\u00e1",
                    "picture": "http://www.aluk.com/uploads/products/images/venta_950x622.png",
                    "thermal_break": false,
                    "non_insulated": false,
                    "wood_solution": false,
                    "bullet_proof": false,
                    "translations": [{
                        "lang": "en",
                        "summary": "A revolutionary and high insulated window and door system.",
                        "application": "<p>Suitable for most standard window and door applications. Ideal for commercial and heavy public sectors, including offices, hospitals, schools and other industrial applications.<br />Suitable for new and refurbished housing.<br />Ideal for low energy rating homes and passive houses.</p>\n",
                        "description": "<p>The revolutionary Vent\u00e1 window and door system offers high level of design and durability and meets the highest standards of insulation. The ABS technology guarantees a minimal heat loss : Uf values \u2265 0.85 W / m\u00b2K.</p>\n",
                        "features_user": "<ul>\n  <li>Excellent acoustic performance results reaching up to 46 dB (on a window of 1230 x 1480 mm).</li>\n  <li>Super insulation : Uf heat value of \u2265 0,85 W/m\u00b2K.</li>\n  <li>Optimal results with high efficiency glazing.</li>\n  <li>Wind resistance of Class 4, hurricane resistant.</li>\n  <li>High water tightness (E1500A).</li>\n  <li>Easy to maintain.</li>\n  <li>Sustainable.</li>\n  <li>Air, wind and water tightness.</li>\n  <li>Anti-burglar.</li>\n</ul>\n",
                        "options": "<ul>\n  <li>A wide range of RAL colors is available in different finishes: gloss, matt, texture, structure, anodisation.</li>\n  <li>Bicolor, a different color on the inside and the outside, is possible.</li>\n</ul>\n"
                    }, {
                        "lang": "fr",
                        "summary": "Un syst\u00e8me de portes et fen\u00eatres r\u00e9volutionnaire et hyper isolant.",
                        "application": "<p>Vent\u00e1 offre une solution pour la plupart des applications standard de portes et fen\u00eatres.<br>\nId\u00e9al pour un usage intensif tel que les bureaux, les h\u00f4pitaux, les \u00e9coles et d\u2019autres applications industrielles.<br>\nId\u00e9al pour les maisons \u00e0 basse consommation et maisons passives.</p>\n",
                        "description": "<p>Les portes et fen\u00eatres Vent\u00e1 offrent un design et une durabilit\u00e9 de haut niveau et r\u00e9pondent aux plus hautes normes d\u2019isolation. La technologie ABS garantit une d\u00e9perdition de chaleur minimale avec des valeurs Uf > 0,85 W/m\u00b2K.</p>\n",
                        "features_user": "<ul>\n  <li>Excellents r\u00e9sultats lors des tests acoustiques (Rw = 46 dB).</li>\n  <li>Super isolant : valeur Uf thermique \u2265 0,85 W/m\u00b2K.</li>\n  <li>R\u00e9sultats optimaux avec des vitrages \u00e0 haut rendement.</li>\n  <li>R\u00e9sistance au vent de classe 4, r\u00e9siste aux ouragans.</li>\n  <li>La plus haute imperm\u00e9abilit\u00e9 du segment (E1500A).</li>\n  <li>Facile \u00e0 entretenir.</li>\n  <li>Durable.</li>\n  <li>\u00c9tanche \u00e0 l\u2019eau, au vent et \u00e0 l\u2019air.</li>\n  <li>Anti-effraction.</li>\n</ul>\n",
                        "options": "<ul>\n  <li>Une large gamme de couleurs RAL est disponible en diff\u00e9rentes finitions: brillant, mat, textur\u00e9, structure m\u00e9tallique et anodisation.</li>\n  <li>Toutes les applications bicolores, avec une couleur diff\u00e9rente pour l\u2019int\u00e9rieur et l\u2019ext\u00e9rieur, sont possibles.</li>\n</ul>\n"
                    }, {
                        "lang": "nl",
                        "summary": "Revolutionair en super isolerend raam-en deursysteem in het b-Quick gamma.",
                        "application": "<p>Vent\u00e1 biedt een oplossing voor de meeste standaard raam-en deur oplossingen. Ideaal voor intensief gebruik, zoals in kantoren, ziekenhuizen, scholen en andere industri\u00eble toepassingen.<br />Bouw en renovatie van een woning.<br />Ideaal voor lage-energiewoningen of passiefwoningen.</p>\n",
                        "description": "<p>Vent\u00e1  is een nieuw en innovatief raamsysteem dat nooit geziene opportuniteiten biedt op het vlak van montage, duurzaamheid en isolatienormen. Door middel van ABS-isolatietechnologie verkrijgen we Uf-waarden vanaf 0,85 W/m\u00b2K.</p>\n",
                        "features_user": "<ul>\n  <li>Uitstekende akoestische  resultaten akoestische (Rw = 46 dB).</li>\n  <li>Super isolatie: Uf waarde \u2265 0,85 W/m\u00b2K.</li>\n  <li>Een optimaal resultaat met hoog rendement beglazing.</li>\n  <li>Weerstand tegen wind: klasse 4  - orkaan bestendig.</li>\n  <li>De hoogste waterdichtheid (E1500A).</li>\n  <li>Gemakkelijk te onderhouden.</li>\n  <li>Duurzaam.</li>\n  <li>Waterdicht, wind en lucht.</li>\n  <li>Inbraakwerend.</li>\n</ul>\n",
                        "options": "<ul>\n  <li>Een breed gamma aan RAL-kleuren is verkrijgbaar in verschillende afwerkingen: glans, mat, textuur, structuurlaken anodisatie.</li>\n  <li>Bicolor, een verschillende kleur aan de binnenkant en de buitenkant, is mogelijk.</li>\n</ul>\n"
                    }],
                    "types": ["33"],
                    "files": [{
                        "id": "295",
                        "file": "http://www.aluk.com/uploads/products/files/venta.png",
                        "translations": [{
                            "lang": "fr",
                            "title": "Section"
                        }, {
                            "lang": "nl",
                            "title": "Section"
                        }]
                    }],
                    "variations": [{
                        "id": "280",
                        "files": [],
                        "translations": [{
                            "lang": "en",
                            "title": "Casement"
                        }, {
                            "lang": "fr",
                            "title": "Frappe"
                        }, {
                            "lang": "nl",
                            "title": "Raam"
                        }],
                        "caracs": {
                            "performances": {
                                "uw_double_glazing": "1,1",
                                "uw_triple_glazing": "0,8",
                                "uf": "1,0",
                                "classification_aww": "4 / E1500A / C4",
                                "rw": "46 (-2;-7)"
                            },
                            "sizelimits": {
                                "max_glass_thick": "75",
                                "max_sash_width": "1400",
                                "max_sash_height": "2400",
                                "max_sash_load": "150"
                            },
                            "solutions": {
                                "inward_opening": true,
                                "bottom_hung": true,
                                "tilt_turn": true
                            },
                            "features": {
                                "multi_point_locking": true,
                                "dual_color": true,
                                "anti_burglar": true
                            }
                        }
                    }, {
                        "id": "291",
                        "files": [],
                        "translations": [{
                            "lang": "en",
                            "title": "Door"
                        }, {
                            "lang": "fr",
                            "title": "Porte"
                        }, {
                            "lang": "nl",
                            "title": "Deur"
                        }],
                        "caracs": {
                            "performances": {
                                "uw_double_glazing": "1,1 (W1060 x H2180)",
                                "uw_triple_glazing": "0,8 (W1060 x H2180)",
                                "uf": "0,9"
                            },
                            "sizelimits": {
                                "max_glass_thick": "75",
                                "max_sash_width": "1250",
                                "max_sash_height": "2500",
                                "max_sash_load": "120"
                            },
                            "solutions": {
                                "inward_opening": true,
                                "outward_opening": true
                            },
                            "features": {
                                "multi_point_locking": true,
                                "dual_color": true,
                                "anti_burglar": true
                            }
                        }
                    }],
                    "projects": [{
                        "id": "223"
                    }]
                }],
                "delete": []
            }
## Check update necessity [/product?country=be%26check=true%26timestamp=1467731234]

### Get update count [GET]

+ Response 200 (application/json)


        {
            "item_count":2,
            "picture_count":5,
            "pictures_size":1254993
        }

## Get update [/product?country=be%26timestamp=1467731234]

### Get updated products list [GET]

+ Response 200 (application/json)


    + Headers

            Item-Count: 2
            Picture-Count: 5
            Pictures-Size: 1254993

    + Body

            {
                "types": [{
                    "id": "40",
                    "picture": {
                        "image": "http://www.aluk.com/uploads/products/images/product-balustrade-list_700x443.jpg",
                        "size": 54233
                    },
                    "translations": [{
                        "lang": "en",
                        "title": "Balustrades"
                    }]
                }, {
                    "id": "39",
                    "picture": {
                        "image": "http://www.aluk.com/uploads/products/images/product-conservatory-list_700x443.jpg",
                        "size": 62078
                    },
                    "translations": [{
                        "lang": "en",
                        "title": "Conservatories"
                    }, {
                        "lang": "fr",
                        "title": "V\u00e9randas"
                    }, {
                        "lang": "nl",
                        "title": "Verandasystemen"
                    }]
                }, {
                    "id": "37",
                    "picture": {
                        "image": "http://www.aluk.com/uploads/products/images/product-curtainwall-list_700x443.jpg",
                        "size": 45183
                    },
                    "translations": [{
                        "lang": "en",
                        "title": "Curtain walls"
                    }, {
                        "lang": "fr",
                        "title": "Fa\u00e7ades"
                    }, {
                        "lang": "nl",
                        "title": "Vliesgevelsystemen"
                    }, {
                        "lang": "zh",
                        "title": "\u5e55\u5899"
                    }]
                }, {
                    "id": "34",
                    "picture": [],
                    "translations": [{
                        "lang": "en",
                        "title": "Door"
                    }]
                }, {
                    "id": "33",
                    "picture": {
                        "image": "http://www.aluk.com/uploads/products/images/product-windows-list_700x443.jpg",
                        "size": 40812
                    },
                    "translations": [{
                        "lang": "fr",
                        "title": "Fen\u00eatres et portes"
                    }, {
                        "lang": "nl",
                        "title": "Raam- en deursystemen"
                    }, {
                        "lang": "en",
                        "title": "Windows and doors"
                    }, {
                        "lang": "zh",
                        "title": "\u7a97\u548c\u95e8"
                    }]
                }, {
                    "id": "36",
                    "picture": {
                        "image": "http://www.aluk.com/uploads/products/images/product-foldingdoor-list_700x443.jpg",
                        "size": 50202
                    },
                    "translations": [{
                        "lang": "en",
                        "title": "Folding doors"
                    }, {
                        "lang": "fr",
                        "title": "Portes repliables"
                    }, {
                        "lang": "nl",
                        "title": "Vouwdeursystemen"
                    }, {
                        "lang": "zh",
                        "title": "\u6298\u53e0\u95e8"
                    }]
                }, {
                    "id": "35",
                    "picture": {
                        "image": "http://www.aluk.com/uploads/products/images/product-slidingdoor-list_700x443.jpg",
                        "size": 43748
                    },
                    "translations": [{
                        "lang": "fr",
                        "title": "Portes coulissantes"
                    }, {
                        "lang": "nl",
                        "title": "Schuifdeursystemen"
                    }, {
                        "lang": "en",
                        "title": "Sliding doors"
                    }, {
                        "lang": "zh",
                        "title": "\u63a8\u62c9\u95e8\u7cfb\u7edf"
                    }]
                }, {
                    "id": "38",
                    "picture": {
                        "image": "http://www.aluk.com/uploads/products/images/product-shutterandlouver-list_700x443.jpg",
                        "size": 67977
                    },
                    "translations": [{
                        "lang": "en",
                        "title": "Shutters and louvers"
                    }]
                }],
                "newOrUpdate": {
                    "0": {
                        "id": "628",
                        "name": "Kolos HI",
                        "picture": "http://www.aluk.com/uploads/products/images/kolos_950x622.png",
                        "thermal_break": false,
                        "non_insulated": false,
                        "wood_solution": false,
                        "bullet_proof": false,
                        "translations": [{
                            "lang": "en",
                            "summary": "A high insulated sliding door system with Spidertechnology.",
                            "application": "<p>Suitable for most standard sliding applications. Ideal for commercial and heavy public sectors, including offices, hospitals, schools and other industrial applications.<br />Suitable for new and refurbished housing.</p>\n",
                            "description": "<p>Kolos is a high insulation sliding window system.</p>\n",
                            "features_user": "<ul>\n  <li>Despite its maximum sash load of 400 kg, the Kolos keeps its natural sleek design.</li>\n  <li>100% compatible with the Triton HI window and door system.</li>\n  <li>Available in monorail, two or three rails, and lift and slide.</li>\n  <li>A 5-point locking system is the standard and can be equipped of anti-burglar glazing beads.</li>\n  <li>Easy to maintain.</li>\n  <li>Sustainable.</li>\n  <li>Air, wind and water tightness.</li>\n</ul>\n",
                            "options": "<ul>\n  <li>A wide range of RAL colors is available in different finishes: gloss, matt, texture, structure, anodisation.</li>\n  <li>Bicolor, a different color on the inside and the outside, is possible.</li>\n</ul>\n"
                        }, {
                            "lang": "fr",
                            "summary": "La porte coulissante hyper isolante avec Spidertechnology.",
                            "application": "<p>Kolos offre une solution adapt\u00e9e \u00e0 la plupart des applications standard de coullissants. Id\u00e9al pour une gamme d\u2019applications des secteurs commercial et public lourds, y compris les bureaux, les h\u00f4pitaux, les \u00e9coles et d\u2019autres applications industrielles.<br />construction et r\u00e9novation d\u2019une maison.</p>\n",
                            "description": "<p>Kolos est le premier syst\u00e8me hyper-isolant pour ch\u00e2ssis coulissants.</p>\n",
                            "features_user": "<ul>\n  <li>En d\u00e9pit du poids maximum par ouvrant de 400 kg, le syst\u00e8me Kolos conserve sa finesse naturelle.</li>\n  <li>100% compatible avec le syst\u00e8me de portes et de fen\u00eatres Triton Hi.</li>\n  <li>Kolos propose des coulissants monorails,  2 rails et un syst\u00e8me levant-coulissant.</li>\n  <li>Une fermeture \u00e0 5 points est le standard et peut \u00eatre \u00e9quip\u00e9 de parcloses antieffraction.</li>\n  <li>Facile \u00e0 entretenir.</li>\n  <li>Durable.</li>\n  <li>\u00c9tanche \u00e0 l\u2019eau, au vent et \u00e0 l\u2019air.</li>\n</ul>\n",
                            "options": "<ul>\n  <li>Une large gamme de couleurs RAL est disponible en diff\u00e9rentes finitions: brillant, mat, textur\u00e9, structure m\u00e9tallique et anodisation.</li>\n  <li>Toutes les applications bicolores, avec une couleur diff\u00e9rente pour l\u2019int\u00e9rieur et l\u2019ext\u00e9rieur, sont possibles.</li>\n</ul>\n"
                        }, {
                            "lang": "nl",
                            "summary": "Hyperisolerende schuifeur met Spidertechnologie.",
                            "application": "<p>Kolos biedt een oplossing voor de meeste standaard raam-en deur oplossingen. Ideaal voor intensief gebruik, zoals in kantoren, ziekenhuizen, scholen en andere industri\u00eble toepassingen.<br />Bouw en renovatie van een woning.<br />Ideaal voor lage-energiewoningen of passiefwoningen.</p>\n",
                            "description": "<p>Kolos is het eerste hoog isolerend schuifdeursysteem.</p>\n",
                            "features_user": "<ul>\n  <li>Hefschuifvleugelgewichten tot 400 kg zijn mogelijk zelfs in combinatie met een slank uiterlijk.</li>\n  <li>Kolos  perfect compatibel en combineerbaar met het Triton HI raam- en deursysteem.</li>\n  <li>Kolos is verkrijgbaar in zowel mono- als duo uitvoering, een hefschuif uitvoering is voorzien.</li>\n  <li>Standaard met een 5-puntsluiting uitgerust en ook inbraakvertragende glaslatten zijn toepasbaar.</li>\n  <li>Makkelijk te onderhouden.</li>\n  <li>Duurzaam.</li>\n  <li>Water-wind- en luchtdicht.</li>\n  <li>Inbraakwerend.</li>\n</ul>\n",
                            "options": "<ul>\n  <li>Een breed gamma aan RAL-kleuren is verkrijgbaar in verschillende afwerkingen: glans, mat, textuur, structuurlaken anodisatie.</li>\n  <li>Bicolor, een verschillende kleur aan de binnenkant en de buitenkant, is mogelijk.</li>\n</ul>\n"
                        }],
                        "types": ["35"],
                        "files": [{
                            "id": "266",
                            "file": "http://www.aluk.com/uploads/products/files/kolos_duo_rail.jpg",
                            "translations": [{
                                "lang": "fr",
                                "title": "Kolos duo rail"
                            }, {
                                "lang": "nl",
                                "title": "Kolos duo rail"
                            }]
                        }, {
                            "id": "267",
                            "file": "http://www.aluk.com/uploads/products/files/kolos_chicane.jpg",
                            "translations": [{
                                "lang": "fr",
                                "title": "Kolos chicane"
                            }, {
                                "lang": "nl",
                                "title": "Kolos chicane"
                            }]
                        }],
                        "variations": [{
                            "id": "295",
                            "files": [],
                            "translations": [{
                                "lang": "en",
                                "title": "Sliding door"
                            }, {
                                "lang": "fr",
                                "title": "Porte coulissante"
                            }, {
                                "lang": "nl",
                                "title": "Schuifdeur"
                            }],
                            "caracs": {
                                "performances": {
                                    "uw_double_glazing": "1,5",
                                    "uw_triple_glazing": "1,2",
                                    "uf": "2,5 (sash in.) / 3,2 (sash out.)",
                                    "classification_aww": "4 / E750A / C4"
                                },
                                "sizelimits": {
                                    "max_glass_thick": "57",
                                    "max_sash_width": "3500",
                                    "max_sash_height": "4000",
                                    "max_sash_load": "400"
                                },
                                "features": {
                                    "multi_point_locking": true,
                                    "dual_color": true
                                }
                            }
                        }],
                        "projects": [{
                            "id": "224"
                        }, {
                            "id": "225"
                        }]
                    },
                    "1": {
                        "id": "677",
                        "name": "Vent\u00e1",
                        "picture": "http://www.aluk.com/uploads/products/images/venta_950x622.png",
                        "thermal_break": false,
                        "non_insulated": false,
                        "wood_solution": false,
                        "bullet_proof": false,
                        "translations": [{
                            "lang": "en",
                            "summary": "A revolutionary and high insulated window and door system.",
                            "application": "<p>Suitable for most standard window and door applications. Ideal for commercial and heavy public sectors, including offices, hospitals, schools and other industrial applications.<br />Suitable for new and refurbished housing.<br />Ideal for low energy rating homes and passive houses.</p>\n",
                            "description": "<p>The revolutionary Vent\u00e1 window and door system offers high level of design and durability and meets the highest standards of insulation. The ABS technology guarantees a minimal heat loss : Uf values \u2265 0.85 W / m\u00b2K.</p>\n",
                            "features_user": "<ul>\n  <li>Excellent acoustic performance results reaching up to 46 dB (on a window of 1230 x 1480 mm).</li>\n  <li>Super insulation : Uf heat value of \u2265 0,85 W/m\u00b2K.</li>\n  <li>Optimal results with high efficiency glazing.</li>\n  <li>Wind resistance of Class 4, hurricane resistant.</li>\n  <li>High water tightness (E1500A).</li>\n  <li>Easy to maintain.</li>\n  <li>Sustainable.</li>\n  <li>Air, wind and water tightness.</li>\n  <li>Anti-burglar.</li>\n</ul>\n",
                            "options": "<ul>\n  <li>A wide range of RAL colors is available in different finishes: gloss, matt, texture, structure, anodisation.</li>\n  <li>Bicolor, a different color on the inside and the outside, is possible.</li>\n</ul>\n"
                        }, {
                            "lang": "fr",
                            "summary": "Un syst\u00e8me de portes et fen\u00eatres r\u00e9volutionnaire et hyper isolant.",
                            "application": "<p>Vent\u00e1 offre une solution pour la plupart des applications standard de portes et fen\u00eatres.<br>\nId\u00e9al pour un usage intensif tel que les bureaux, les h\u00f4pitaux, les \u00e9coles et d\u2019autres applications industrielles.<br>\nId\u00e9al pour les maisons \u00e0 basse consommation et maisons passives.</p>\n",
                            "description": "<p>Les portes et fen\u00eatres Vent\u00e1 offrent un design et une durabilit\u00e9 de haut niveau et r\u00e9pondent aux plus hautes normes d\u2019isolation. La technologie ABS garantit une d\u00e9perdition de chaleur minimale avec des valeurs Uf > 0,85 W/m\u00b2K.</p>\n",
                            "features_user": "<ul>\n  <li>Excellents r\u00e9sultats lors des tests acoustiques (Rw = 46 dB).</li>\n  <li>Super isolant : valeur Uf thermique \u2265 0,85 W/m\u00b2K.</li>\n  <li>R\u00e9sultats optimaux avec des vitrages \u00e0 haut rendement.</li>\n  <li>R\u00e9sistance au vent de classe 4, r\u00e9siste aux ouragans.</li>\n  <li>La plus haute imperm\u00e9abilit\u00e9 du segment (E1500A).</li>\n  <li>Facile \u00e0 entretenir.</li>\n  <li>Durable.</li>\n  <li>\u00c9tanche \u00e0 l\u2019eau, au vent et \u00e0 l\u2019air.</li>\n  <li>Anti-effraction.</li>\n</ul>\n",
                            "options": "<ul>\n  <li>Une large gamme de couleurs RAL est disponible en diff\u00e9rentes finitions: brillant, mat, textur\u00e9, structure m\u00e9tallique et anodisation.</li>\n  <li>Toutes les applications bicolores, avec une couleur diff\u00e9rente pour l\u2019int\u00e9rieur et l\u2019ext\u00e9rieur, sont possibles.</li>\n</ul>\n"
                        }, {
                            "lang": "nl",
                            "summary": "Revolutionair en super isolerend raam-en deursysteem in het b-Quick gamma.",
                            "application": "<p>Vent\u00e1 biedt een oplossing voor de meeste standaard raam-en deur oplossingen. Ideaal voor intensief gebruik, zoals in kantoren, ziekenhuizen, scholen en andere industri\u00eble toepassingen.<br />Bouw en renovatie van een woning.<br />Ideaal voor lage-energiewoningen of passiefwoningen.</p>\n",
                            "description": "<p>Vent\u00e1  is een nieuw en innovatief raamsysteem dat nooit geziene opportuniteiten biedt op het vlak van montage, duurzaamheid en isolatienormen. Door middel van ABS-isolatietechnologie verkrijgen we Uf-waarden vanaf 0,85 W/m\u00b2K.</p>\n",
                            "features_user": "<ul>\n  <li>Uitstekende akoestische  resultaten akoestische (Rw = 46 dB).</li>\n  <li>Super isolatie: Uf waarde \u2265 0,85 W/m\u00b2K.</li>\n  <li>Een optimaal resultaat met hoog rendement beglazing.</li>\n  <li>Weerstand tegen wind: klasse 4  - orkaan bestendig.</li>\n  <li>De hoogste waterdichtheid (E1500A).</li>\n  <li>Gemakkelijk te onderhouden.</li>\n  <li>Duurzaam.</li>\n  <li>Waterdicht, wind en lucht.</li>\n  <li>Inbraakwerend.</li>\n</ul>\n",
                            "options": "<ul>\n  <li>Een breed gamma aan RAL-kleuren is verkrijgbaar in verschillende afwerkingen: glans, mat, textuur, structuurlaken anodisatie.</li>\n  <li>Bicolor, een verschillende kleur aan de binnenkant en de buitenkant, is mogelijk.</li>\n</ul>\n"
                        }],
                        "types": ["33"],
                        "files": [{
                            "id": "295",
                            "file": "http://www.aluk.com/uploads/products/files/venta.png",
                            "translations": [{
                                "lang": "fr",
                                "title": "Section"
                            }, {
                                "lang": "nl",
                                "title": "Section"
                            }]
                        }],
                        "variations": [{
                            "id": "280",
                            "files": [],
                            "translations": [{
                                "lang": "en",
                                "title": "Casement"
                            }, {
                                "lang": "fr",
                                "title": "Frappe"
                            }, {
                                "lang": "nl",
                                "title": "Raam"
                            }],
                            "caracs": {
                                "performances": {
                                    "uw_double_glazing": "1,1",
                                    "uw_triple_glazing": "0,8",
                                    "uf": "1,0",
                                    "classification_aww": "4 / E1500A / C4",
                                    "rw": "46 (-2;-7)"
                                },
                                "sizelimits": {
                                    "max_glass_thick": "75",
                                    "max_sash_width": "1400",
                                    "max_sash_height": "2400",
                                    "max_sash_load": "150"
                                },
                                "solutions": {
                                    "inward_opening": true,
                                    "bottom_hung": true,
                                    "tilt_turn": true
                                },
                                "features": {
                                    "multi_point_locking": true,
                                    "dual_color": true,
                                    "anti_burglar": true
                                }
                            }
                        }, {
                            "id": "291",
                            "files": [],
                            "translations": [{
                                "lang": "en",
                                "title": "Door"
                            }, {
                                "lang": "fr",
                                "title": "Porte"
                            }, {
                                "lang": "nl",
                                "title": "Deur"
                            }],
                            "caracs": {
                                "performances": {
                                    "uw_double_glazing": "1,1 (W1060 x H2180)",
                                    "uw_triple_glazing": "0,8 (W1060 x H2180)",
                                    "uf": "0,9"
                                },
                                "sizelimits": {
                                    "max_glass_thick": "75",
                                    "max_sash_width": "1250",
                                    "max_sash_height": "2500",
                                    "max_sash_load": "120"
                                },
                                "solutions": {
                                    "inward_opening": true,
                                    "outward_opening": true
                                },
                                "features": {
                                    "multi_point_locking": true,
                                    "dual_color": true,
                                    "anti_burglar": true
                                }
                            }
                        }],
                        "projects": [{
                            "id": "223"
                        }]
                    }
                },
                "delete": [
                    "604"
                ]
            }